homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqttserv
  keepalive: 60
  password: mqtt_broker_pass
  reject_unauthorized: true
  user: mqtt_broker_user
  version: 4
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
devices:
